# Generated by Django 4.2 on 2023-05-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_category_alter_product_descriptions_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
